package com.example.skillexchange.ui.theme

import androidx.compose.ui.graphics.Color

// Premium Government-Ready Palette
// Navy Blue for Authority, Emerald for Growth, Slate for Cleanliness

val md_theme_light_primary = Color(0xFF0056D2)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDFF1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001945)
val md_theme_light_secondary = Color(0xFF006B3F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD2F8E0)
val md_theme_light_onSecondaryContainer = Color(0xFF002110)
val md_theme_light_tertiary = Color(0xFF5D5E7D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE2E0FF)
val md_theme_light_onTertiaryContainer = Color(0xFF191A2C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8F9FA)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFE1E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44474E)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFFADC6FF)

val md_theme_dark_primary = Color(0xFFADC6FF)
val md_theme_dark_onPrimary = Color(0xFF002E69)
val md_theme_dark_primaryContainer = Color(0xFF004494)
val md_theme_dark_onPrimaryContainer = Color(0xFFD8E2FF)
val md_theme_dark_secondary = Color(0xFFB7D3C5)
val md_theme_dark_onSecondary = Color(0xFF003822)
val md_theme_dark_secondaryContainer = Color(0xFF005234)
val md_theme_dark_onSecondaryContainer = Color(0xFFD2F8E0)
val md_theme_dark_tertiary = Color(0xFFC6C5EB)
val md_theme_dark_onTertiary = Color(0xFF2F304D)
val md_theme_dark_tertiaryContainer = Color(0xFF454664)
val md_theme_dark_onTertiaryContainer = Color(0xFFE2E0FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E6)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF44474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_outline = Color(0xFF8E9199)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E6)
val md_theme_dark_inversePrimary = Color(0xFF005AC1)
